/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsPosture {
  root: string
  rootfs: string
  mounts: Array<Array<string>>
  shares: Array<Array<string>>
  network: string
  display?: string
  sound: boolean
  gpu: boolean
  results: boolean
  env: Array<string>
  vcpus: number
  memMib: number
}
export interface JsFile {
  path: string
  sizeBytes: number
}
export interface JsRun {
  runId: string
  name: string
  verb: string
  command: Array<string>
  posture: JsPosture
  startedMs: number
  endedMs?: number
  endKind?: string
  endCode?: number
  pid?: number
  stdout?: string
  stderr?: string
  stdoutBytes?: number
  stderrBytes?: number
  outputTruncated?: boolean
  files?: Array<JsFile>
  dir?: string
  live?: boolean
  /**
   * Whether the guest command itself succeeded. A non-zero exit is a result, not an error, so
   * this is the field a caller branches on.
   */
  ok: boolean
}
export declare function runSandbox(name: string | undefined | null, command: Array<string>, root: string | undefined | null, vcpus: number | undefined | null, memMib: number | undefined | null, workdir: string | undefined | null, mounts: Array<Array<string>>, shares: Array<Array<string>>, net: string | undefined | null, rootfs: string | undefined | null, env: Array<string>, noResults: boolean, keep: boolean, dryRun: boolean, gpu: boolean, sound: boolean): JsRun
/** One filed run, by id or by name — the lookup `tormoni show` makes. */
export declare function show(id: string): JsRun
/** The filed runs, newest first. Without `all`, only the ones still open. */
export declare function runs(all?: boolean | undefined | null): Array<JsRun>
