// The record shapes are NOT defined here. `JsRun`, `JsPosture` and `JsFile` in `index.d.ts` are
// generated by napi from the Rust structs in `src/models.rs`, so the type a caller sees is
// derived from `boxdesk_record::Record` rather than written beside it and kept in step by hand.
// Only the INPUT types below are this SDK's own vocabulary, because they answer to no Rust struct.
import type { JsFile, JsPosture, JsRun } from "../index";

export type Run = JsRun;
export type Posture = JsPosture;
export type RunFile = JsFile;

/**
 * How a run finished.
 *
 * `null` while a run is still going, and on a dry run — which never starts.
 * Never parse a single string to learn how a run ended: read `endKind` first,
 * then `endCode`, which carries a number only for `"exit"` and `"signal"`.
 */
export type EndKind = "exit" | "signal" | "stopped" | "gone" | "failed" | "unknown";

/** `none` is no network at all; `tsi` lets the guest reach what the host can. */
export type Network = "none" | "tsi";

export type RootfsMode = "read-only" | "writable";

/**
 * Options for `run` and `dryRun`. Each maps onto exactly one flag of
 * `boxdesk run`; anything left out is left off the command line, so the CLI's
 * own defaults stand.
 */
export interface RunOptions {
  /** `--root DIR` — guest root tree. */
  root?: string;
  /** `--vcpus N` */
  vcpus?: number;
  /** `--mem MIB` — guest RAM in MiB. */
  mem?: number;
  /** `--workdir DIR` — guest working directory. */
  workdir?: string;
  /** `--mount GUESTDIR=HOSTDIR` — a host directory, read-write, at a guest path. */
  mounts?: Array<[guestDir: string, hostDir: string]>;
  /** `--share TAG=HOSTPATH` — an extra virtiofs device the guest mounts by tag. */
  shares?: Array<[tag: string, hostPath: string]>;
  /** `--net none|tsi` */
  net?: Network;
  /** `--rootfs read-only|writable` */
  rootfs?: RootfsMode;
  /**
   * `--env KEY=VALUE` — one guest environment entry per pair. The guest gets the
   * whole entry; the record keeps only the name, in {@link Posture.env}.
   */
  env?: Record<string, string>;
  /** `--name NAME` — names the sandbox. */
  name?: string;
  /** `--no-results` — drops the default `/results` mount. */
  noResults?: boolean;
  /**
   * `--keep` — file the run's record instead of sweeping it.
   *
   * A run is ephemeral by default: its output comes back in the result and the
   * directory it worked in goes with it, so {@link Run.files} is empty and
   * {@link Run.dir} is null. Keep it when you mean to read what the guest wrote
   * to `/results`, or to reach the run again with `show`.
   */
  keep?: boolean;
  /** `--gpu` — refused by a host whose libkrun was built without the backend. */
  gpu?: boolean;
  /** `--sound` — refused by a host whose libkrun was built without the backend. */
  sound?: boolean;
  /** `--display WxH[@HZ]` — does not currently boot on macOS. */
  display?: string;
}
